# Generated by Django 3.0.8 on 2021-01-11 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0003_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='Post',
            new_name='post',
        ),
    ]
